# TODO: 需修改的配置，用于上传到 CloudFlare
name = "blogroll"
type = "webpack"
account_id = "1be59dcab5a04acec1bbbb9e4deee8ea"
workers_dev = true
# route = "blogroll.icl.moe/*"
zone_id = "691f6aa5d9b5c986c09a92cc27394d51"

[site]
bucket = "./web/dist"
entry-point = "workers-site"
